[package]
name = "proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "gRPC protocol definitions"
license.workspace = true
repository.workspace = true

[dependencies]
tonic = "0.13"
prost = "0.13"

[build-dependencies]
tonic-build = "0.13" 