[package]
name = "proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "gRPC protocol definitions"
license.workspace = true
repository.workspace = true

[dependencies]
tonic = "0.10"
prost = "0.12"

[build-dependencies]
tonic-build = "0.10" 